/* =========================================================
   THERMPYX - TOPIC BASED THERMODYNAMICS QUIZ
========================================================= */

/* =========================================================
   1. QUIZ DATA
========================================================= */
const quizTopics = {
    heat: {
        name: "Heat & Temperature",
        questions: [
            {
                question: "What is the SI unit of heat energy?",
                options: ["Joule", "Watt", "Pascal", "Kelvin"],
                answer: "Joule",
                explanation: "The SI unit of heat energy is the joule (J)."
            },
            {
                question: "Which equation is commonly used to calculate heat transferred during a temperature change?",
                options: ["Q = mcΔT", "W = PΔV", "PV = nRT", "ΔU = Q − W"],
                answer: "Q = mcΔT",
                explanation: "For sensible heating or cooling, heat transfer is calculated using Q = mcΔT."
            },
            {
                question: "How does heat naturally flow between two objects at different temperatures?",
                options: [
                    "From lower to higher temperature",
                    "From higher to lower temperature",
                    "It does not flow",
                    "It always flows toward the larger object"
                ],
                answer: "From higher to lower temperature",
                explanation: "Heat naturally transfers from a higher-temperature region to a lower-temperature region."
            },
            {
                question: "What does specific heat capacity describe?",
                options: [
                    "Energy required to raise the temperature of unit mass by one degree",
                    "Pressure generated by one mole of gas",
                    "Work done per unit time",
                    "Volume occupied by one joule of energy"
                ],
                answer: "Energy required to raise the temperature of unit mass by one degree",
                explanation: "Specific heat capacity tells us how much energy is needed to raise the temperature of a unit mass by one degree."
            },
            {
                question: "If an object's final temperature is lower than its initial temperature, what is the sign of ΔT = Tfinal − Tinitial?",
                options: ["Positive", "Negative", "Always zero", "Undefined"],
                answer: "Negative",
                explanation: "When Tfinal is lower than Tinitial, subtracting the larger initial temperature gives a negative ΔT."
            }
        ]
    },

    work: {
        name: "Work & Energy",
        questions: [
            {
                question: "For a constant-pressure expansion, which expression represents boundary work?",
                options: ["W = PΔV", "Q = mcΔT", "PV = nRT", "P = F/A only"],
                answer: "W = PΔV",
                explanation: "At constant pressure, boundary work is pressure multiplied by the change in volume."
            },
            {
                question: "When a gas expands against its surroundings, what happens to its volume?",
                options: ["It increases", "It decreases", "It remains zero", "It becomes negative"],
                answer: "It increases",
                explanation: "Expansion means the system occupies a larger volume."
            },
            {
                question: "Internal energy is best described as which type of property?",
                options: ["A state property", "A path only", "A unit of pressure", "A type of volume"],
                answer: "A state property",
                explanation: "Internal energy depends on the state of the system, not on the path used to reach that state."
            },
            {
                question: "If the volume does not change during a process, what is the boundary work W = PΔV?",
                options: ["Zero", "Maximum", "Always negative", "Equal to heat transfer"],
                answer: "Zero",
                explanation: "With no change in volume, ΔV = 0, so boundary work is zero."
            },
            {
                question: "Which SI unit is used for both work and energy?",
                options: ["Joule", "Pascal", "Kelvin", "Meter"],
                answer: "Joule",
                explanation: "Work and energy are both measured in joules (J) in SI units."
            }
        ]
    },

    "first-law": {
        name: "First Law of Thermodynamics",
        questions: [
            {
                question: "Which equation represents the First Law using the convention that W is work done by the system?",
                options: ["ΔU = Q − W", "Q = mcΔT", "PV = nRT", "W = P/V"],
                answer: "ΔU = Q − W",
                explanation: "With work done by the system taken as positive, the First Law is ΔU = Q − W."
            },
            {
                question: "A system receives 1000 J of heat and does 300 J of work. What is ΔU?",
                options: ["700 J", "1300 J", "300 J", "−700 J"],
                answer: "700 J",
                explanation: "Using ΔU = Q − W gives 1000 J − 300 J = 700 J."
            },
            {
                question: "In the First Law, which quantity represents energy transferred because of a temperature difference?",
                options: ["Heat (Q)", "Work (W)", "Volume (V)", "Pressure (P)"],
                answer: "Heat (Q)",
                explanation: "Q represents heat transfer between the system and surroundings."
            },
            {
                question: "For a complete thermodynamic cycle, what is the net change in internal energy?",
                options: ["Zero", "Always positive", "Always negative", "Equal to pressure"],
                answer: "Zero",
                explanation: "A cycle returns to its initial state, so the state property internal energy has no net change."
            },
            {
                question: "Which statement best expresses the energy-conservation idea behind the First Law?",
                options: [
                    "Energy can change form but is conserved",
                    "Energy can be created from nothing",
                    "Heat and work are always equal",
                    "Pressure must remain constant"
                ],
                answer: "Energy can change form but is conserved",
                explanation: "The First Law is the thermodynamic statement of conservation of energy."
            }
        ]
    },

    processes: {
        name: "Thermodynamic Processes",
        questions: [
            {
                question: "Which thermodynamic process occurs at constant temperature?",
                options: ["Isothermal", "Isobaric", "Isochoric", "Adiabatic"],
                answer: "Isothermal",
                explanation: "An isothermal process occurs while temperature remains constant."
            },
            {
                question: "Which thermodynamic process occurs at constant pressure?",
                options: ["Isobaric", "Isothermal", "Isochoric", "Adiabatic"],
                answer: "Isobaric",
                explanation: "An isobaric process occurs at constant pressure."
            },
            {
                question: "Which thermodynamic process occurs at constant volume?",
                options: ["Isochoric", "Isothermal", "Isobaric", "Adiabatic"],
                answer: "Isochoric",
                explanation: "An isochoric process occurs at constant volume."
            },
            {
                question: "In an ideal adiabatic process, what is the heat transfer Q?",
                options: ["Q = 0", "Q > 0 always", "Q < 0 always", "Q = PΔV always"],
                answer: "Q = 0",
                explanation: "An adiabatic process is defined by no heat transfer between the system and surroundings."
            },
            {
                question: "On a P-V diagram, an isochoric process is represented by which kind of line?",
                options: ["Vertical line", "Horizontal line", "Circular path", "Always a diagonal line"],
                answer: "Vertical line",
                explanation: "Because volume stays constant, the process remains at one x-axis position on a P-V diagram."
            }
        ]
    }
};

const allMaterialQuestionCount = 12;

/* =========================================================
   2. HELPERS
========================================================= */
function shuffleArray(array) {
    const shuffled = [...array];

    for (let i = shuffled.length - 1; i > 0; i--) {
        const randomIndex = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[randomIndex]] = [shuffled[randomIndex], shuffled[i]];
    }

    return shuffled;
}

function buildAllMaterialsQuiz() {
    const topicKeys = Object.keys(quizTopics);
    const selected = [];

    // Three randomized questions from each topic keeps the mixed quiz balanced.
    topicKeys.forEach(function (topicKey) {
        selected.push(...shuffleArray(quizTopics[topicKey].questions).slice(0, 3));
    });

    return shuffleArray(selected).slice(0, allMaterialQuestionCount);
}

/* =========================================================
   3. ELEMENTS
========================================================= */
const quizTopicSelector = document.getElementById("quizTopicSelector");
const quizTopicCards = document.querySelectorAll(".quiz-topic-card");
const quizContainer = document.getElementById("quizContainer");
const quizResult = document.getElementById("quizResult");
const quizQuestionNumber = document.getElementById("quizQuestionNumber");
const quizScore = document.getElementById("quizScore");
const quizProgressBar = document.getElementById("quizProgressBar");
const questionText = document.getElementById("questionText");
const quizOptions = document.getElementById("quizOptions");
const quizFeedback = document.getElementById("quizFeedback");
const quizNextButton = document.getElementById("quizNextButton");
const quizFinalScore = document.getElementById("quizFinalScore");
const quizFinalMessage = document.getElementById("quizFinalMessage");
const quizRestartButton = document.getElementById("quizRestartButton");
const quizChangeTopicButton = document.getElementById("quizChangeTopicButton");
const quizChooseTopicButton = document.getElementById("quizChooseTopicButton");
const quizTopicName = document.getElementById("quizTopicName");
const quizResultTopic = document.getElementById("quizResultTopic");

/* =========================================================
   4. QUIZ STATE
========================================================= */
let selectedTopic = null;
let selectedTopicName = "";
let shuffledQuestions = [];
let currentQuestion = 0;
let score = 0;
let answered = false;

/* =========================================================
   5. SCREEN MANAGEMENT
========================================================= */
function showTopicSelection() {
    selectedTopic = null;
    selectedTopicName = "";
    shuffledQuestions = [];
    currentQuestion = 0;
    score = 0;
    answered = false;

    quizTopicSelector.hidden = false;
    quizContainer.hidden = true;
    quizContainer.style.display = "";
    quizResult.classList.remove("show");

    quizTopicSelector.scrollIntoView({ behavior: "smooth", block: "start" });
}

function startQuiz(topicKey) {
    selectedTopic = topicKey;
    currentQuestion = 0;
    score = 0;
    answered = false;

    if (topicKey === "all") {
        selectedTopicName = "All Materials";
        shuffledQuestions = buildAllMaterialsQuiz();
    } else if (quizTopics[topicKey]) {
        selectedTopicName = quizTopics[topicKey].name;
        shuffledQuestions = shuffleArray(quizTopics[topicKey].questions);
    } else {
        return;
    }

    quizTopicName.textContent = selectedTopicName;
    quizResultTopic.textContent = selectedTopicName;

    quizTopicSelector.hidden = true;
    quizResult.classList.remove("show");
    quizContainer.hidden = false;
    quizContainer.style.display = "block";

    loadQuestion();
    quizContainer.scrollIntoView({ behavior: "smooth", block: "start" });
}

/* =========================================================
   6. LOAD QUESTION
========================================================= */
function loadQuestion() {
    const current = shuffledQuestions[currentQuestion];

    if (!current) {
        showResult();
        return;
    }

    quizQuestionNumber.textContent =
        `Question ${currentQuestion + 1} of ${shuffledQuestions.length}`;
    quizScore.textContent = `Score: ${score}`;
    questionText.textContent = current.question;

    const progressPercentage =
        ((currentQuestion + 1) / shuffledQuestions.length) * 100;
    quizProgressBar.style.width = `${progressPercentage}%`;

    quizOptions.innerHTML = "";
    quizFeedback.textContent = "";
    quizFeedback.className = "quiz-feedback";
    quizNextButton.disabled = true;
    quizNextButton.textContent = "NEXT";
    answered = false;

    const shuffledOptions = shuffleArray(current.options);

    shuffledOptions.forEach(function (option) {
        const button = document.createElement("button");
        button.type = "button";
        button.className = "quiz-option";
        button.textContent = option;
        button.dataset.answer = option;
        button.addEventListener("click", function () {
            selectAnswer(button);
        });
        quizOptions.appendChild(button);
    });
}

/* =========================================================
   7. SELECT ANSWER
========================================================= */
function selectAnswer(selectedButton) {
    if (answered) {
        return;
    }

    answered = true;

    const selectedAnswer = selectedButton.dataset.answer;
    const current = shuffledQuestions[currentQuestion];
    const correctAnswer = current.answer;
    const explanation = current.explanation;
    const allOptions = quizOptions.querySelectorAll(".quiz-option");

    allOptions.forEach(function (button) {
        button.disabled = true;
    });

    if (selectedAnswer === correctAnswer) {
        score++;
        selectedButton.classList.add("correct");
        quizFeedback.textContent = `Correct! ${explanation}`;
        quizFeedback.classList.add("correct");
    } else {
        selectedButton.classList.add("incorrect");

        allOptions.forEach(function (button) {
            if (button.dataset.answer === correctAnswer) {
                button.classList.add("correct");
            }
        });

        quizFeedback.textContent = `Incorrect. ${explanation}`;
        quizFeedback.classList.add("incorrect");
    }

    quizScore.textContent = `Score: ${score}`;
    quizNextButton.disabled = false;

    if (currentQuestion === shuffledQuestions.length - 1) {
        quizNextButton.textContent = "SEE RESULT";
    }
}

/* =========================================================
   8. RESULT
========================================================= */
function showResult() {
    window.TPXHistory?.log("quiz", selectedTopicName || "Practice Quiz",
      `${score} / ${shuffledQuestions.length}`, location.href);
    quizContainer.style.display = "none";
    quizContainer.hidden = true;
    quizResult.classList.add("show");
    quizResultTopic.textContent = selectedTopicName;
    quizFinalScore.textContent = `${score} / ${shuffledQuestions.length}`;

    const percentage = shuffledQuestions.length
        ? (score / shuffledQuestions.length) * 100
        : 0;

    if (percentage === 100) {
        quizFinalMessage.textContent = "Excellent! You got every question correct.";
    } else if (percentage >= 80) {
        quizFinalMessage.textContent = "Great job! You have a strong understanding of this material.";
    } else if (percentage >= 60) {
        quizFinalMessage.textContent = "Good effort! Review a few concepts and try again.";
    } else {
        quizFinalMessage.textContent = "Keep learning! Review the theory and try the quiz again.";
    }

    quizResult.scrollIntoView({ behavior: "smooth", block: "start" });
}

/* =========================================================
   9. EVENTS
========================================================= */
quizTopicCards.forEach(function (card) {
    card.addEventListener("click", function () {
        startQuiz(card.dataset.topic);
    });
});

if (quizNextButton) {
    quizNextButton.addEventListener("click", function () {
        if (!answered) {
            return;
        }

        quizNextButton.disabled = true;
        currentQuestion++;

        if (currentQuestion < shuffledQuestions.length) {
            loadQuestion();
        } else {
            showResult();
        }
    });
}

if (quizRestartButton) {
    quizRestartButton.addEventListener("click", function () {
        if (selectedTopic) {
            startQuiz(selectedTopic);
        }
    });
}

if (quizChangeTopicButton) {
    quizChangeTopicButton.addEventListener("click", showTopicSelection);
}

if (quizChooseTopicButton) {
    quizChooseTopicButton.addEventListener("click", showTopicSelection);
}

/* =========================================================
   10. INITIAL STATE
========================================================= */
if (quizTopicSelector && quizContainer && quizResult) {
    quizTopicSelector.hidden = false;
    quizContainer.hidden = true;
    quizResult.classList.remove("show");
}

console.log("THERMPYX Quiz: topic selection ready.");
